### ISSUE TITLE
Authentication headers

### ISSUE THREAD

**Issue by fennelhans** [eerimoq/gqt#2]
I need to be able to pass a bearer token in my auth headers. How do I go about doing that?

**Comment by eerimoq** [comment]
gqt -e https://api.github.com/graphql -H "Authorization: bearer ghp_<value>"

**Comment by fennelhans** [comment]
Awesome. Thank you.

**Comment by fennelhans** [comment]
Actually... doesn't seem to be working:

```shell
usage: gqt [-h] [--version] [-e ENDPOINT] [-r] [-y] [-q] [-c] [-p] [-C] [--no-verify]
gqt: error: unrecognized arguments: -H Authorization: bearer ghp_[...]
```

Version 0.59.0

**Comment by eerimoq** [comment]
It was probably implemented in a later release. Try to update. Something like `pip install -U gqt` depending on your setup.
