### ISSUE TITLE
gqt does not allow to ignore e.g. self signed ssl certificate errors

### ISSUE THREAD

**Issue by fwolfst** [eerimoq/gqt#4]
In development often self signed ssl certs are used. gqt will raise an error when these are encountered (even if they are accepted in the systems certificate store in Mac OS, I believe).

Adding an option to ignore these errors or giving instructions (ENV var?) how to overcome this would be very welcome.

Most likely passing an command line argument to requests.post (`verify:`) would be the way to implement (https://www.w3schools.com/python/ref_requests_post.asp)? Not a pythonist here.

**Comment by eerimoq** [comment]
Did you try `--no-verify`?

**Comment by fwolfst** [comment]
Thanks for all the work and the swift answer!
No I didn't; was too much in the hurry and thought "let's at least leave a comment". Works like a charm! `--help` would indeed have helped.

What do you think about putting the output of `gqt --help` in the README (I think CTRL-F'ed the README for 'verify' and 'ssl')? If you thumb up I could craft a PR for that.

**Comment by eerimoq** [comment]
Sure, sounds like a good idea that will help other as well.
