### ISSUE TITLE
Making calls with required fields that have a default

### ISSUE THREAD

**Issue by svanharmelen** [eerimoq/gqt#5]
Hi 👋🏻 

I am trying to switch from mainly using `GraphiQL` to using `gqt` on the command-line to sweeten my workflow, but I encountered a few obstacle that make it a little annoying to switch.

We have a few fields (for example pagination options in our list calls) that are required, but have a default. So as a user in `GraphiQL` I can simply omit those fields, but `gqt` doesn't let me make the query without manually specifying values for these fields.

Is there an option to change/fix that?

And also I noticed something about being able to search, that is not implemented right? It does sound like a very helpful feature for some of the bigger API's out there 😏 

And last question, is there any way I can define my own key mapping?

Thanks!!

**Comment by eerimoq** [comment]
Give version 0.125.3 a try (available on PyPI). I implemented what I think is a fix for default value on required fields, at least for scalar, enum and other simple fields.

**Comment by svanharmelen** [comment]
Thanks for your quick response! I just tried 0.125.3, but when I try to open/select a method which has a default object it crashes with this error 🙈
 
<img width="276" alt="image" src="https://github.com/eerimoq/gqt/assets/4171547/2b579519-9566-463f-9314-d9b1ed15ae4c">

**Comment by svanharmelen** [comment]
For reference, the object is something like:

```grapghl
input Pagination {
  page: Int! = 10,
  perPage: Int! = 25
}
```

**Comment by svanharmelen** [comment]
It doesn't give me more output then that one line I'm afraid (so maybe crashing isn't the right word, but it closes and gives the above error).

**Comment by eerimoq** [comment]
I see. I created a new release that might fix it. If not, I'll revert everything and test more before creating another release.

**Comment by svanharmelen** [comment]
I can test it in just a little, will let you know the result. Thanks!!

**Comment by svanharmelen** [comment]
Yes, it works! Very nice! Thanks for that, help a lot in being able to use the tool 👍🏻 

Any feedback on the search and mapping features? Is that something that is already possible or maybe planned in the future?

But regardless, I can start to play with it now. Thanks!

**Comment by eerimoq** [comment]
Happy to help!

I did partly implement the search feature some time ago, but I removed it in commit 92460ff41d1af2ddcc0cdffd3f83b239316e5757. Can't remember the reason, but it was probably mostly because I didn't use it and it added complexity to the code base.

I'm mainly working on another project right now, but feel free to implement the search feature and I'll review.

**Comment by eerimoq** [comment]
Would probably be a good idea to show the default value next to the field for information.

**Comment by svanharmelen** [comment]
Thanks... Not sure if my Python foo is up-to-date enough, but maybe I'll have a look 😏 We have quite a large API, so search would be a game changer for being able to navigate around the API nicely (and will probably make custom mappings unneeded).

I'll close this one as that main question is resolved. Thanks again and have a good weekend 👋🏻
